name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports: ['27017:27017']
        options: >-
          --replSet=rs0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Init replica set (needed for transactions)
      - run: |
          mongosh --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]})"
          for i in {1..30}; do
            STATE=$(mongosh --quiet --eval "rs.status().myState" localhost:27017); \
            if [ "$STATE" = "1" ]; then break; fi; sleep 1; done

      - run: npm ci
        working-directory: server

      - run: npm test
        working-directory: server
        env:
          NODE_ENV: development
          ADMIN_EMAIL:
          ADMIN_PASSWORD: password
          ADMIN_USERNAME: admin
          AUTH_TYPE: SFA
          CAPTCHA_PRIVATE_KEY: unsecureKey
          DB_CONNECTION_STRING: mongodb://localhost:27017/testdb?replicaSet=rs0
          DOMAIN: localhost
          PORT: 8080
          RECOGNIZED_CLIENTS: LOCALHOST
          RECOGNIZED_MARKUP_DOMAINS: https://www.youtube.com, https://player.vimeo.com, https://open.spotify.com, //www.instagram.com/embed.js, https://platform.twitter.com
          SERVED_AT_PATH: /api
          SMTP_AUTH_PASSWORD:
          SMTP_AUTH_USERNAME:
          SMTP_DISPLAY_USERNAME:
          SMTP_HOST:
          SMTP_PORT:
          SMTP_RECEIVER_EMAIL:
          TOKEN_PRIVATE_KEY: unsecureKey
	  
